# Generated by Django 4.2.13 on 2024-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_servicepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='ongoing', max_length=200),
        ),
    ]
