# Generated by Django 4.2.13 on 2024-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldprice',
            old_name='localPrice',
            new_name='usdtoz',
        ),
        migrations.RemoveField(
            model_name='goldprice',
            name='mining',
        ),
        migrations.RemoveField(
            model_name='goldprice',
            name='worldPrice',
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perGramLocalTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perGramLocalUsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perGramWordTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perGramWordUsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perKgLocalTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perKgLocalUsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perKgWordTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='perKgWordUsd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
