# Generated by Django 4.2.13 on 2024-12-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_goldprice_pergramlocaltzs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='perGramLocalTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perGramLocalUsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perGramWordTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perGramWordUsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perKgLocalTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perKgLocalUsd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perKgWordTzs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='perKgWordUsd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
