# Generated by Django 4.2.13 on 2024-12-07 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_goldprice_pergramlocaltzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='uploadedDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
